# Generated by Django 5.2.15 on 2026-06-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("separator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="mode",
            field=models.CharField(choices=[("2stems", "Two Stems")], max_length=16),
        ),
    ]
